project_id = "dssbduklgbmxezpjpuen"

[functions.send-show-notification]
verify_jwt = true

[functions.create-paymongo-session]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false

[functions.verify-paymongo-payment]
verify_jwt = false

[functions.claim-tickets]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.create-manual-payment]
verify_jwt = false

[functions.approve-manual-payment]
verify_jwt = false

[functions.start-trial]
verify_jwt = false

[functions.scan-ticket]
verify_jwt = false

[functions.send-collab-proposal]
verify_jwt = true
